name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main       # only main branch push par deploy hoga
  pull_request:
    branches:
      - main
    types: [synchronize]  # sirf PR update par chalega

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # 2. Setup Node.js 22 (Vite requirement)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          cd ClientApp
          npm install

      # 4. Create .env.production file from secrets
      - name: Create .env.production
        run: |
          cd ClientApp
          echo "VITE_API_BASE_URL=${{ secrets.API_URL }}" >> .env.production

      # 5. Build React App
      - name: Build React App
        run: |
          cd ClientApp
          npm run build

      # 6. Deploy to Azure Static Web Apps
      - name: Deploy to Azure
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_WAVE_0E5730300 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./ClientApp"
          api_location: ""              
          output_location: "dist"       

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_WAVE_0E5730300 }}
          action: "close"